TARGET := iphone:clang:latest:14.0
ARCHS = arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = TelegramMenuTweak

TelegramMenuTweak_FILES = Tweak.x
TelegramMenuTweak_CFLAGS = -fobjc-arc
TelegramMenuTweak_FRAMEWORKS = UIKit Foundation

include $(THEOS_MAKE_PATH)/tweak.mk

